### ISSUE TITLE
Unable to size beyond 999px

### ISSUE THREAD

**Issue by Justinzobel** [psifidotos/applet-latte-spacer#1]
Unable to size beyond 999px.

I've added two spacers but it seems a bit hacky.

However there is a gap between the latte dock and the end of the panel.

Github wouldn't let me paste it, so imgur link:
https://i.imgur.com/qWejWsP.png

**Comment by psifidotos** [comment]
Why do you want Latte spacer with Latte panels?
Remove all of them and just use the proper alignment, Justify I think is the case for your workflow.
