### ISSUE TITLE
[Feature request] Add configurable middle-click and double-click actions

### ISSUE THREAD

**Issue by emvaized** [psifidotos/applet-latte-spacer#2]
I would love to configure latte-spacer to fill all the available width, and then assign some custom click actions to it - for example, middle mouse click to open System monitor. 
Would it be possible to implement? Thanks.

**Comment by psifidotos** [comment]
This is possible to implement but not for this applet. This applet is just to add an empty spacing at all cases. Unfortunately either you need to create it on your own or to find a developer that is interested in this and he ia going to create a new applet with such options.
