### ISSUE TITLE
IOTM doesn't shrink in size with two latte spacers (one on both sides) as it does with plasma spacer

### ISSUE THREAD

**Issue by amifelipek** [psifidotos/applet-latte-spacer#3]
with applet-latte-spacer:
![with-latte-spacer](https://user-images.githubusercontent.com/52990296/112879104-187d5980-909f-11eb-9c04-c1b9b2059d41.png)

with default plasma spacer:
![with-plasma-spacer](https://user-images.githubusercontent.com/52990296/112879109-1b784a00-909f-11eb-9d5f-306339ebe6bb.png)

**Comment by psifidotos** [comment]
Latte spacer can not center widgets in plasma panels. This is why plasma specific centered spacers are used in plasma panels.

As long as this is solved from official plasma spacer why do you need support from latte spacers to support it?

**Comment by amifelipek** [comment]
With plasma spacers when some hidden tray entry is shown causes the IOTM to flicker, latte dock's Justify widget doesn't do that, so wanted to test if it flicker with this widget.

Anyway thank you for answering!

**Comment by psifidotos** [comment]
Flickering for plasma panels I dont think it can be avoided. The trick in Latte is not on spacers. Latte is showing Justify splitters in users but it does not use them at all for layouting. In Latte centered applets are inside a centered sublayout that does not care at all for surrounding applets.

**Comment by FHEK789** [comment]
Just one more question: the only reason right now I'm not using latte-dock is because the margin separator widget doesn't work, am I missing some configuration option or is this not possible yet?
