### ISSUE TITLE
Request - mode to allow centered clock

### ISSUE THREAD

**Issue by reubenfirmin** [psifidotos/applet-latte-spacer#4]
My top panel is as follows:

[Applications Icon][Global Menu][Latte Spacer][Clock][Latte Spacer][Systray]

I have both Latte Spacers configured to "use available space". It would be great if they were somehow aware of each other and could balance the space so that the clock stayed exactly centered.

In reality what happens is that changes in the Global Menu size (when switching apps) or systray size (notifications, for example) cause the clock to shift about in the middle.

**Comment by psifidotos** [comment]
from Plasma you need to use plasma panel spacer for Latte you have Justify mode, end of story

out of this applet resposibility

**Comment by reubenfirmin** [comment]
Plasma panel spacer doesn't do it either. I used your spacer because it's smarter. No desire to add the feature though - fair enough.

**Comment by psifidotos** [comment]
> Plasma panel spacer doesn't do it either. I used your spacer because it's smarter. No desire to add the feature though - fair enough.

they do it, if they dont do it you should file a bug to plasma
